# .github/workflows/main.yml
name: Standalone CLI
on: [push, pull_request]

jobs:
  machineStandalone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Fluid Attacks Skims with Docker
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app docker.io/fluidattacks/skims:latest skims scan ./config.yaml

      - name: Upload scan report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: fluidattacks-report
          path: Fluid-Attacks-Results.csv
