# .github/workflows/main.yml
name: Standalone CLI
on: [push, pull_request]

jobs:
  machineStandalone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Fluid Attacks Skims with Docker
        uses: docker://docker.io/fluidattacks/skims:latest
        with:
          args: skims --strict scan ./config.yaml
          
      - name: Upload scan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fluidattacks-report
          path: Fluid-Attacks-Results.csv
